# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roommatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roommatch
  pod 'Parse'
  pod 'Parse/UI'

  target 'RoommatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoommatchUITests' do
    # Pods for testing
  end

end
